services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

volumes:
  esdata01:


# {
#   "name" : "89b2f1f6f61f",
#   "cluster_name" : "docker-cluster",
#   "cluster_uuid" : "h4FNu_o5RIKqh_55K47LEA",
#   "version" : {
#     "number" : "8.14.3",
#     "build_flavor" : "default",
#     "build_type" : "docker",
#     "build_hash" : "d55f984299e0e88dee72ebd8255f7ff130859ad0",
#     "build_date" : "2024-07-07T22:04:49.882652950Z",
#     "build_snapshot" : false,
#     "lucene_version" : "9.10.0",
#     "minimum_wire_compatibility_version" : "7.17.0",
#     "minimum_index_compatibility_version" : "7.0.0"
#   },
#   "tagline" : "You Know, for Search"
# }