# Generated by Django 5.0.4 on 2024-08-24 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.colorvariant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('size_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sizevariant')),
            ],
            options={
                'unique_together': {('product', 'color_variant', 'size_variant')},
            },
        ),
    ]
