# Generated by Django 5.0.4 on 2024-09-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productvariant_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mwk_flag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
